---
driver:
  name: vagrant
  provider: vmware_fusion
  network:
    - ["forwarded_port", {guest: 80, host: 8080}]

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[filestore::default]
    verifier:
      inspec_tests:
        - test/recipes
  - name: localstore
    driver:
      vm_hostname: filestore.local
      synced_folders:
        - ["/Users/[[HOST_PATH_TO_FILES]]", "/var/www/filestore/", "create: true"]
    run_list:
      - recipe[filestore::default]
